version: "3.9"

services:
  backend:
    build: .
    depends_on:
      - postgres
    ports:
    - 8000
    environment:
      SERVICE: backend
  scheduler:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      SERVICE: beat
      DJANGO_SETTINGS_MODULE: easycar.settings
  worker1:
    build: .
    depends_on:
      - postgres
      - redis
      - scheduler
    environment:
      SERVICE: worker
      DJANGO_SETTINGS_MODULE: easycar.settings
      QUEUES: "celery,cars"
      C_FORCE_ROOT: 1
  worker2:
    build: .
    depends_on:
      - postgres
      - redis
      - scheduler
    environment:
      SERVICE: worker
      DJANGO_SETTINGS_MODULE: easycar.settings
      QUEUES: "celery,models"
      C_FORCE_ROOT: 1
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432
  redis:
    image: redis
    ports:
    - 6379
  nginx:
    image: nginx
    depends_on:
      - backend
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
