version: "3.9"

services:
  backend:
    build: .
    depends_on:
      - postgres
    ports:
    - 8000
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432
  nginx:
    image: nginx
    depends_on:
      - backend
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
