# Generated by Django 3.2.2 on 2021-05-16 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cars', '0003_car'), ('cars', '0004_alter_car_vin'), ('cars', '0005_alter_car_owner'), ('cars', '0006_car_image'), ('cars', '0007_alter_car_image'), ('cars', '0008_alter_car_image'), ('cars', '0009_alter_car_image'), ('cars', '0010_alter_car_image')]

    dependencies = [
        ('cars', '0002_auto_20210511_2154'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, help_text='Car vin number', max_length=64, null=True)),
                ('year', models.IntegerField(help_text='Car released year')),
                ('model', models.OneToOneField(blank=True, help_text='Car model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.model')),
                ('owner', models.ForeignKey(help_text='Car owner', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(blank=True, max_length=2048, null=True, upload_to='')),
            ],
        ),
    ]
