# Generated by Django 3.2.2 on 2021-05-17 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('cars', '0004_auto_20210517_1739'), ('cars', '0005_auto_20210517_1806'), ('cars', '0006_alter_model_name')]

    dependencies = [
        ('cars', '0003_car_squashed_0010_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='make',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='make',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='car',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='make',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(help_text='Car model', max_length=128, unique=True),
        ),
    ]
