# Generated by Django 3.2.2 on 2021-05-16 21:59

from django.db import migrations
from django.db.models.functions import Upper, Lower


def migrate(apps, schema):
    Make = apps.get_model('cars', 'Make')
    Make.objects.update(name=Upper('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210517_1739_squashed_0006_alter_model_name'),
    ]

    operations = [
        migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop)
    ]
